name: GitHub Actions Demo
on: 
  push:
    branches: 
      - main
      - dev
      - zhper-patch-1
  pull_request:
    branches:
      - main
      - dev
      - zhper-patch-1
    
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: npm init
        run: npm init -y
      - name: Install npm dependencies
        run: npm install
      - name: Run build task
        run: npm run build --if-present
